import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1761420624371 implements MigrationInterface {
    name = 'InitialSchema1761420624371'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cultivos" ("pk_id_cultivo" uuid NOT NULL DEFAULT uuid_generate_v4(), "cul_estado" smallint NOT NULL DEFAULT '1', "cul_siembra" date, CONSTRAINT "PK_bca07ab50918efd3cbfa5d751f9" PRIMARY KEY ("pk_id_cultivo"))`);
        await queryRunner.query(`CREATE TABLE "tipo_cultivo" ("pk_id_tipo_cultivo" uuid NOT NULL DEFAULT uuid_generate_v4(), "tpc_nombre" character varying(50) NOT NULL, "tpc_es_perenne" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_587358c5f6b5c8b443435ab7e7a" PRIMARY KEY ("pk_id_tipo_cultivo"))`);
        await queryRunner.query(`CREATE TABLE "variedad" ("pk_id_variedad" uuid NOT NULL DEFAULT uuid_generate_v4(), "var_nombre" character varying(50) NOT NULL, "fk_id_tipo_cultivo" uuid, CONSTRAINT "PK_969ecd3cd1b6413cddb77780f29" PRIMARY KEY ("pk_id_variedad"))`);
        await queryRunner.query(`CREATE TABLE "cultivos_x_variedad" ("pk_id_cultivos_x_variedad" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_id_cultivo" uuid NOT NULL, "fk_id_variedad" uuid NOT NULL, CONSTRAINT "PK_08252ea88874d61f1b3e9061574" PRIMARY KEY ("pk_id_cultivos_x_variedad"))`);
        await queryRunner.query(`CREATE TABLE "tipo_sensor" ("pk_id_tipo_sensor" uuid NOT NULL DEFAULT uuid_generate_v4(), "tps_nombre" character varying(50) NOT NULL, "tps_descripcion" text, "tps_unidad_medida" character varying(20) NOT NULL, CONSTRAINT "PK_cd37a52a5c0b91ac14da63b4ce7" PRIMARY KEY ("pk_id_tipo_sensor"))`);
        await queryRunner.query(`CREATE TABLE "mqtt_config" ("pk_id_mqtt_config" uuid NOT NULL DEFAULT uuid_generate_v4(), "mc_nombre" character varying(100) NOT NULL, "mc_host" character varying(255) NOT NULL, "mc_port" integer NOT NULL, "mc_protocol" character varying(10) NOT NULL, "mc_topic_base" character varying(255) NOT NULL, "mc_activa" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_8c821100a5c36655ac2c5010f10" PRIMARY KEY ("pk_id_mqtt_config"))`);
        await queryRunner.query(`CREATE TABLE "zona_mqtt_config" ("pk_id_zona_mqtt_config" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_id_mqtt_config" uuid NOT NULL, "fk_id_zona" uuid NOT NULL, "zmc_estado" boolean NOT NULL DEFAULT true, "zmc_created_at" TIMESTAMP NOT NULL DEFAULT now(), "zmc_updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_764b7bca78c91fb0737c627eba4" PRIMARY KEY ("pk_id_zona_mqtt_config"))`);
        await queryRunner.query(`CREATE TABLE "medicion_sensor" ("pk_id_medicion" uuid NOT NULL DEFAULT uuid_generate_v4(), "med_key" character varying(50) NOT NULL, "med_valor" numeric(10,2) NOT NULL, "med_fecha_medicion" TIMESTAMP NOT NULL, "fk_id_zona_mqtt_config" uuid NOT NULL, CONSTRAINT "PK_93f31099faa603caa41f2311044" PRIMARY KEY ("pk_id_medicion"))`);
        await queryRunner.query(`CREATE TABLE "sensor" ("pk_id_sensor" uuid NOT NULL DEFAULT uuid_generate_v4(), "sen_nombre" character varying(50) NOT NULL, "sen_coor_x" integer NOT NULL, "sen_coor_y" integer NOT NULL, "sen_rango_minimo" numeric(10,2), "sen_rango_maximo" numeric(10,2), "sen_img" character varying(255) NOT NULL, "sen_estado" smallint NOT NULL, "sen_fecha_instalacion" TIMESTAMP NOT NULL, "sen_fecha_ultimo_mantenimiento" TIMESTAMP, "fk_id_tipo_sensor" uuid NOT NULL, "fk_id_zona" uuid, CONSTRAINT "PK_29eb369add2b5d73d5d64f1f140" PRIMARY KEY ("pk_id_sensor"))`);
        await queryRunner.query(`CREATE TABLE "zonas" ("pk_id_zona" uuid NOT NULL DEFAULT uuid_generate_v4(), "zon_nombre" character varying(50) NOT NULL, "zon_tipo_lote" character varying(8) NOT NULL, "zon_coor_x" numeric(10,2) NOT NULL, "zon_coor_y" numeric(10,2) NOT NULL, "zon_area_metros_cuadrados" numeric(10,2), "zon_coordenadas" jsonb, CONSTRAINT "PK_ed479402d4f4ca15c7d322f09a9" PRIMARY KEY ("pk_id_zona"))`);
        await queryRunner.query(`CREATE TABLE "modulos" ("pk_id_modulo" uuid NOT NULL DEFAULT uuid_generate_v4(), "modulo_nombre" character varying(100) NOT NULL, CONSTRAINT "UQ_923a92db6231b5b2f2f7e9e5da2" UNIQUE ("modulo_nombre"), CONSTRAINT "PK_8a063140bc741bfecd07b24ff37" PRIMARY KEY ("pk_id_modulo"))`);
        await queryRunner.query(`CREATE TABLE "recursos" ("pk_id_recurso" uuid NOT NULL DEFAULT uuid_generate_v4(), "recurso_nombre" character varying(100) NOT NULL, "fk_id_modulo" uuid NOT NULL, CONSTRAINT "UQ_b6b0becd16a7805a3abd2e8040f" UNIQUE ("recurso_nombre"), CONSTRAINT "PK_d7248e07fcefff849f1ed05b519" PRIMARY KEY ("pk_id_recurso"))`);
        await queryRunner.query(`CREATE TABLE "permisos" ("pk_id_permiso" uuid NOT NULL DEFAULT uuid_generate_v4(), "permiso_accion" character varying(50) NOT NULL, "fk_id_recurso" uuid NOT NULL, CONSTRAINT "UQ_94249bd4792ad592f51009b994f" UNIQUE ("permiso_accion", "fk_id_recurso"), CONSTRAINT "PK_cd8cb3a868a07cac7c78792b49a" PRIMARY KEY ("pk_id_permiso"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("pk_id_rol" uuid NOT NULL DEFAULT uuid_generate_v4(), "rol_nombre" character varying(50) NOT NULL, CONSTRAINT "UQ_96aaed1c729577ea6fe99348402" UNIQUE ("rol_nombre"), CONSTRAINT "PK_3bf67137b7498d0800050e57c72" PRIMARY KEY ("pk_id_rol"))`);
        await queryRunner.query(`CREATE TABLE "fichas" ("pk_id_ficha" uuid NOT NULL DEFAULT uuid_generate_v4(), "ficha_numero" bigint NOT NULL, CONSTRAINT "UQ_d4cf2c92f89757be2ba36a82edc" UNIQUE ("ficha_numero"), CONSTRAINT "PK_ffb584f563667ba25e5d371bced" PRIMARY KEY ("pk_id_ficha"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("pk_id_usuario" uuid NOT NULL DEFAULT uuid_generate_v4(), "usu_dni" bigint NOT NULL, "usu_nombres" character varying(50) NOT NULL, "usu_apellidos" character varying(50) NOT NULL, "usu_password_h" character varying(255) NOT NULL, "usu_telefono" bigint NOT NULL, "usu_correo" character varying(255) NOT NULL, "fk_id_rol" uuid, "fk_id_ficha" uuid, CONSTRAINT "PK_51cd6eda4d00711d8046b3371b5" PRIMARY KEY ("pk_id_usuario"))`);
        await queryRunner.query(`CREATE TABLE "usuarios_x_actividades" ("pk_id_usuarios_x_actividades" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_id_usuario" uuid NOT NULL, "fk_id_actividad" uuid NOT NULL, "uxa_fecha_asignacion" date NOT NULL, "uxa_activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_27916d7e87d22241cc58c494ed1" PRIMARY KEY ("pk_id_usuarios_x_actividades"))`);
        await queryRunner.query(`CREATE TABLE "categoria_actividad" ("pk_id_categoria_actividad" uuid NOT NULL DEFAULT uuid_generate_v4(), "cat_nombre" character varying(50) NOT NULL, CONSTRAINT "PK_58979ee7414cf605e61ac6c1559" PRIMARY KEY ("pk_id_categoria_actividad"))`);
        await queryRunner.query(`CREATE TABLE "categoria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(100) NOT NULL, "descripcion" text, "esDivisible" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_6771d90221138c5bf48044fd73d" UNIQUE ("nombre"), CONSTRAINT "PK_f027836b77b84fb4c3a374dc70d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unidades_medida" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(50) NOT NULL, "abreviatura" character varying(10) NOT NULL, CONSTRAINT "UQ_e051424ff38ab456319a8e87d1f" UNIQUE ("nombre"), CONSTRAINT "UQ_c737574555e77ba8b2b1d0a10bc" UNIQUE ("abreviatura"), CONSTRAINT "PK_b299f0e6758c0c02ae3e729232a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "productos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(150) NOT NULL, "descripcion" text NOT NULL, "sku" character varying(50) NOT NULL, "precioCompra" numeric(12,2) NOT NULL, "capacidadPresentacion" numeric(10,2) NOT NULL DEFAULT '1.00', "fk_categoria_id" uuid NOT NULL, "fk_unidad_medida_id" uuid NOT NULL, "img_url" character varying(255), "vida_util_promedio_por_usos" integer, CONSTRAINT "UQ_805687bf24c1411756fbd37b2f3" UNIQUE ("sku"), CONSTRAINT "PK_04f604609a0949a7f3b43400766" PRIMARY KEY ("id")); COMMENT ON COLUMN "productos"."vida_util_promedio_por_usos" IS 'Vida útil promedio en usos para productos no divisibles (herramientas)'`);
        await queryRunner.query(`CREATE TABLE "bodega" ("pk_id_bodega" uuid NOT NULL DEFAULT uuid_generate_v4(), "bod_numero" character varying(15) NOT NULL, "bod_nombre" character varying(100) NOT NULL, CONSTRAINT "PK_f1488a686bf47ab88f6e9b079a8" PRIMARY KEY ("pk_id_bodega"))`);
        await queryRunner.query(`CREATE TABLE "lotes_inventario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_producto_id" uuid NOT NULL, "fk_bodega_id" uuid NOT NULL, "cantidadDisponible" numeric(10,2) NOT NULL DEFAULT '0', "stock" numeric(10,2) NOT NULL DEFAULT '0', "esParcial" boolean NOT NULL DEFAULT false, "cantidadParcial" numeric(10,2) NOT NULL DEFAULT '0', "fechaIngreso" TIMESTAMP NOT NULL DEFAULT now(), "fechaVencimiento" date, CONSTRAINT "PK_d53c42ed86b9c606e6e923e36ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "estados_reserva" ("id" SERIAL NOT NULL, "nombre" character varying(50) NOT NULL, CONSTRAINT "UQ_23c6cbdee88a8bbe1b1e383c46d" UNIQUE ("nombre"), CONSTRAINT "PK_86d5fa4092e03881e284db998f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservas_x_actividad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_actividad_id" uuid NOT NULL, "fk_lote_id" uuid NOT NULL, "fk_estado_id" integer NOT NULL, "cantidad_reservada" numeric(10,2) NOT NULL, "cantidad_usada" numeric(10,2), "cantidad_devuelta" numeric(10,2), "capacidad_presentacion_producto" numeric(10,2) NOT NULL, "precio_producto" numeric(12,2) NOT NULL, CONSTRAINT "PK_fe5573623a0c475c374ba2c6e89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades" ("pk_id_actividad" uuid NOT NULL DEFAULT uuid_generate_v4(), "act_descripcion" text NOT NULL, "act_fecha_asignacion" date NOT NULL, "act_horas_dedicadas" numeric, "act_precio_hora" numeric, "act_observacion" character varying(255), "act_estado" boolean DEFAULT true, "act_fecha_finalizacion" TIMESTAMP, "act_img_url" character varying(255), "fk_id_cultivo_variedad_x_zona" uuid NOT NULL, "fk_id_categoria_actividad" uuid NOT NULL, CONSTRAINT "PK_0da23a7b5690826fcc0853856ad" PRIMARY KEY ("pk_id_actividad"))`);
        await queryRunner.query(`CREATE TABLE "estados_fenologicos" ("id" SERIAL NOT NULL, "nombre" character varying(50) NOT NULL, "descripcion" text, "orden" integer NOT NULL, CONSTRAINT "UQ_fe1ec40c26cebf2476203bb4b54" UNIQUE ("nombre"), CONSTRAINT "PK_2dfc94837481f30efa5e7adcda1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cultivos_variedad_x_zona" ("pk_id_cv_zona" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_id_cultivos_x_variedad" uuid NOT NULL, "fk_id_zona" uuid NOT NULL, "cvz_cantidad_plantas_inicial" integer NOT NULL DEFAULT '0', "cvz_cantidad_plantas_actual" integer NOT NULL DEFAULT '0', "fk_estado_fenologico" integer, "cvz_fecha_actualizacion" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_26b6aa02204bf2010c4120ee902" PRIMARY KEY ("pk_id_cv_zona"))`);
        await queryRunner.query(`CREATE TABLE "cosechas_ventas" ("pk_id_cosechas_ventas" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_id_cosecha" uuid NOT NULL, "fk_id_venta" uuid NOT NULL, "cv_cantidad_vendida" numeric(10,2) NOT NULL, CONSTRAINT "PK_d447866486f82a99ef2867f1d38" PRIMARY KEY ("pk_id_cosechas_ventas"))`);
        await queryRunner.query(`CREATE TABLE "cosechas" ("pk_id_cosecha" uuid NOT NULL DEFAULT uuid_generate_v4(), "cos_unidad_medida" character varying(2) NOT NULL, "cos_cantidad" numeric(10,2) NOT NULL, "cos_fecha" date, "cos_rendimiento_por_planta" numeric(10,2), "cos_cantidad_plantas_cosechadas" integer, "cos_cerrado" boolean NOT NULL DEFAULT false, "fk_id_cultivos_variedad_x_zona" uuid NOT NULL, CONSTRAINT "PK_bbbe964394805bbf4b0c03f620e" PRIMARY KEY ("pk_id_cosecha"))`);
        await queryRunner.query(`CREATE TABLE "venta" ("pk_id_venta" uuid NOT NULL DEFAULT uuid_generate_v4(), "ven_cantidad" numeric(10,2) NOT NULL, "ven_fecha" date NOT NULL, "fk_id_cosecha" uuid NOT NULL, "ven_unidad_medida" character varying(2) NOT NULL, "ven_precio_unitario" numeric(10,2) NOT NULL, "ven_precio_kilo" numeric(10,2) NOT NULL, CONSTRAINT "PK_9e09d8f553efa44c3a81f51db78" PRIMARY KEY ("pk_id_venta"))`);
        await queryRunner.query(`CREATE TABLE "tipos_movimiento" ("id" SERIAL NOT NULL, "nombre" character varying(50) NOT NULL, CONSTRAINT "UQ_8dc34bd609546a65f1702961433" UNIQUE ("nombre"), CONSTRAINT "PK_a006012b08b4c5d1249edfb727e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cultivos_x_epa" ("pk_id_cultivos_x_epa" uuid NOT NULL DEFAULT uuid_generate_v4(), "cxp_fecha_deteccion" date NOT NULL, "cxp_estado" smallint NOT NULL, "fk_id_cultivos_x_variedad" uuid NOT NULL, "fk_id_epa" uuid NOT NULL, CONSTRAINT "PK_50265e93fa52fa016463f1c1d91" PRIMARY KEY ("pk_id_cultivos_x_epa"))`);
        await queryRunner.query(`CREATE TABLE "epa" ("pk_id_epa" uuid NOT NULL DEFAULT uuid_generate_v4(), "epa_nombre" character varying(100) NOT NULL, "epa_descripcion" text, "epa_img_url" character varying(255), "fk_id_tipo_epa" uuid NOT NULL, CONSTRAINT "PK_9a3b902c7db65928623ec6598a9" PRIMARY KEY ("pk_id_epa"))`);
        await queryRunner.query(`CREATE TABLE "tipo_epa" ("pk_id_tipo_epa" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_epa_nombre" character varying(50) NOT NULL, CONSTRAINT "UQ_d9e54d57338afcad4d7c91b0d7c" UNIQUE ("tipo_epa_nombre"), CONSTRAINT "PK_dcc91f7443ac39c48ed98eccdf9" PRIMARY KEY ("pk_id_tipo_epa"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_inventario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_lote_id" uuid NOT NULL, "fk_reserva_id" uuid, "fk_tipo_movimiento_id" integer NOT NULL, "cantidad" numeric(10,2) NOT NULL, "fecha_movimiento" TIMESTAMP NOT NULL DEFAULT now(), "observacion" text, CONSTRAINT "PK_812f6e4f95b017981363c4b9ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finanzas_cosecha" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fk_cosecha_id" uuid NOT NULL, "cantidad_cosechada" numeric(10,2) NOT NULL, "precio_por_kilo" numeric(10,2) NOT NULL, "fecha_venta" date, "cantidad_vendida" numeric(10,2) NOT NULL DEFAULT '0', "costo_inventario" numeric(12,2) NOT NULL DEFAULT '0', "costo_mano_obra" numeric(12,2) NOT NULL DEFAULT '0', "costo_total_produccion" numeric(12,2) NOT NULL DEFAULT '0', "ingresos_totales" numeric(12,2) NOT NULL DEFAULT '0', "ganancias" numeric(12,2) NOT NULL DEFAULT '0', "margen_ganancia" numeric(5,2) NOT NULL DEFAULT '0', "fecha_calculo" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0bad71ac77052a79a7b242fa0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("pk_id_session" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_token_hash" character varying(255) NOT NULL, "session_expires_at" TIMESTAMP NOT NULL, "session_is_active" boolean NOT NULL DEFAULT true, "session_created_at" TIMESTAMP NOT NULL DEFAULT now(), "session_updated_at" TIMESTAMP NOT NULL DEFAULT now(), "fk_id_usuario" uuid, CONSTRAINT "PK_854b0cbf57826eeb92786fd61fe" PRIMARY KEY ("pk_id_session"))`);
        await queryRunner.query(`CREATE TABLE "roles_permisos" ("rol_id" uuid NOT NULL, "permiso_id" uuid NOT NULL, CONSTRAINT "PK_0e1dbe0449ae37ef1b31b0d9474" PRIMARY KEY ("rol_id", "permiso_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc3cfbcce511233d4bef92d7e3" ON "roles_permisos" ("rol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef10d9983fcb45f0024cc7000d" ON "roles_permisos" ("permiso_id") `);
        await queryRunner.query(`CREATE TABLE "rol_creacion_jerarquia" ("rol_creador_id" uuid NOT NULL, "rol_creable_id" uuid NOT NULL, CONSTRAINT "PK_9a6a7f47a3cf5c9bb058133556a" PRIMARY KEY ("rol_creador_id", "rol_creable_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b25d18dffadb2e4dbbf66c901" ON "rol_creacion_jerarquia" ("rol_creador_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_06907d494f397996a2d85c0eb6" ON "rol_creacion_jerarquia" ("rol_creable_id") `);
        await queryRunner.query(`ALTER TABLE "variedad" ADD CONSTRAINT "FK_32531335d0482591eae661efcbf" FOREIGN KEY ("fk_id_tipo_cultivo") REFERENCES "tipo_cultivo"("pk_id_tipo_cultivo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_variedad" ADD CONSTRAINT "FK_3869d84e502689591c987724be9" FOREIGN KEY ("fk_id_cultivo") REFERENCES "cultivos"("pk_id_cultivo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_variedad" ADD CONSTRAINT "FK_f625a8d56b4c1e1f18fa2ad8bc7" FOREIGN KEY ("fk_id_variedad") REFERENCES "variedad"("pk_id_variedad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zona_mqtt_config" ADD CONSTRAINT "FK_3ae20521bac657fa2aab70ea611" FOREIGN KEY ("fk_id_mqtt_config") REFERENCES "mqtt_config"("pk_id_mqtt_config") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zona_mqtt_config" ADD CONSTRAINT "FK_6f9527f65f4d638fef8bfe33e8f" FOREIGN KEY ("fk_id_zona") REFERENCES "zonas"("pk_id_zona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medicion_sensor" ADD CONSTRAINT "FK_a02dcc38c6502973912168b35b4" FOREIGN KEY ("fk_id_zona_mqtt_config") REFERENCES "zona_mqtt_config"("pk_id_zona_mqtt_config") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sensor" ADD CONSTRAINT "FK_48052e061c57447d62f9e64b3da" FOREIGN KEY ("fk_id_tipo_sensor") REFERENCES "tipo_sensor"("pk_id_tipo_sensor") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sensor" ADD CONSTRAINT "FK_317e3ed127d5183a466383d910b" FOREIGN KEY ("fk_id_zona") REFERENCES "zonas"("pk_id_zona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recursos" ADD CONSTRAINT "FK_f24d13798abb62d00be138dfc83" FOREIGN KEY ("fk_id_modulo") REFERENCES "modulos"("pk_id_modulo") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permisos" ADD CONSTRAINT "FK_1def2cd2fbc57f21d1547db508c" FOREIGN KEY ("fk_id_recurso") REFERENCES "recursos"("pk_id_recurso") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_dec89f7cdc37cf746fc82ff6034" FOREIGN KEY ("fk_id_rol") REFERENCES "roles"("pk_id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_2b6534c9d14ac35826764cdc118" FOREIGN KEY ("fk_id_ficha") REFERENCES "fichas"("pk_id_ficha") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_x_actividades" ADD CONSTRAINT "FK_58a5178734438394ee03a24949a" FOREIGN KEY ("fk_id_usuario") REFERENCES "usuarios"("pk_id_usuario") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_x_actividades" ADD CONSTRAINT "FK_399398e334d7c22d172a9a4fb9b" FOREIGN KEY ("fk_id_actividad") REFERENCES "actividades"("pk_id_actividad") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_a3004a9c834ee05f56e3b3b921c" FOREIGN KEY ("fk_categoria_id") REFERENCES "categoria"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_ba1bbf9b0181a3be093de57a6f8" FOREIGN KEY ("fk_unidad_medida_id") REFERENCES "unidades_medida"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes_inventario" ADD CONSTRAINT "FK_48dcf6942ce0b80afc4e30c7f80" FOREIGN KEY ("fk_producto_id") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes_inventario" ADD CONSTRAINT "FK_378dc45fa7f862f19f316d5dd06" FOREIGN KEY ("fk_bodega_id") REFERENCES "bodega"("pk_id_bodega") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" ADD CONSTRAINT "FK_b7a58e288f2aff52bf3ac2eb6c3" FOREIGN KEY ("fk_actividad_id") REFERENCES "actividades"("pk_id_actividad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" ADD CONSTRAINT "FK_b504e905dc2a3de3a0500e8973d" FOREIGN KEY ("fk_lote_id") REFERENCES "lotes_inventario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" ADD CONSTRAINT "FK_48e34f436100b175050202792d5" FOREIGN KEY ("fk_estado_id") REFERENCES "estados_reserva"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_4ff147ed17e8bdeb0a22232cf5b" FOREIGN KEY ("fk_id_cultivo_variedad_x_zona") REFERENCES "cultivos_variedad_x_zona"("pk_id_cv_zona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_40f52a18a6b1e8efd9a4938bfec" FOREIGN KEY ("fk_id_categoria_actividad") REFERENCES "categoria_actividad"("pk_id_categoria_actividad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" ADD CONSTRAINT "FK_bedc232cd8a0b1aba926d53af68" FOREIGN KEY ("fk_id_cultivos_x_variedad") REFERENCES "cultivos_x_variedad"("pk_id_cultivos_x_variedad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" ADD CONSTRAINT "FK_959fe9d6787940b232ff5442540" FOREIGN KEY ("fk_id_zona") REFERENCES "zonas"("pk_id_zona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" ADD CONSTRAINT "FK_df819fa89f42a3fb674de12574e" FOREIGN KEY ("fk_estado_fenologico") REFERENCES "estados_fenologicos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cosechas_ventas" ADD CONSTRAINT "FK_bade37bec1231cf147fbcac413e" FOREIGN KEY ("fk_id_cosecha") REFERENCES "cosechas"("pk_id_cosecha") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cosechas_ventas" ADD CONSTRAINT "FK_5563c73e32fef530f3a140ce3bd" FOREIGN KEY ("fk_id_venta") REFERENCES "venta"("pk_id_venta") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cosechas" ADD CONSTRAINT "FK_07c03f265c04076ea27e439632d" FOREIGN KEY ("fk_id_cultivos_variedad_x_zona") REFERENCES "cultivos_variedad_x_zona"("pk_id_cv_zona") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "venta" ADD CONSTRAINT "FK_1b5df15fa07acae8d18b095d5dc" FOREIGN KEY ("fk_id_cosecha") REFERENCES "cosechas"("pk_id_cosecha") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_epa" ADD CONSTRAINT "FK_62ec7f2dad568439e62f7896b73" FOREIGN KEY ("fk_id_cultivos_x_variedad") REFERENCES "cultivos_x_variedad"("pk_id_cultivos_x_variedad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_epa" ADD CONSTRAINT "FK_e93725ad163564397db9100ca2d" FOREIGN KEY ("fk_id_epa") REFERENCES "epa"("pk_id_epa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "epa" ADD CONSTRAINT "FK_25cd948e2b067f238871a478ce7" FOREIGN KEY ("fk_id_tipo_epa") REFERENCES "tipo_epa"("pk_id_tipo_epa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_b635c8408938f63578ad3a441d5" FOREIGN KEY ("fk_lote_id") REFERENCES "lotes_inventario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_ed669516597c2d98f49817c9814" FOREIGN KEY ("fk_reserva_id") REFERENCES "reservas_x_actividad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "FK_8a915d5adf1b954fc3fb4469a2d" FOREIGN KEY ("fk_tipo_movimiento_id") REFERENCES "tipos_movimiento"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finanzas_cosecha" ADD CONSTRAINT "FK_9ee882a201359367555803d307b" FOREIGN KEY ("fk_cosecha_id") REFERENCES "cosechas"("pk_id_cosecha") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_1ab7dcfb69b30ddcdab1d564750" FOREIGN KEY ("fk_id_usuario") REFERENCES "usuarios"("pk_id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" ADD CONSTRAINT "FK_dc3cfbcce511233d4bef92d7e3b" FOREIGN KEY ("rol_id") REFERENCES "roles"("pk_id_rol") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" ADD CONSTRAINT "FK_ef10d9983fcb45f0024cc7000d3" FOREIGN KEY ("permiso_id") REFERENCES "permisos"("pk_id_permiso") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rol_creacion_jerarquia" ADD CONSTRAINT "FK_1b25d18dffadb2e4dbbf66c901c" FOREIGN KEY ("rol_creador_id") REFERENCES "roles"("pk_id_rol") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rol_creacion_jerarquia" ADD CONSTRAINT "FK_06907d494f397996a2d85c0eb67" FOREIGN KEY ("rol_creable_id") REFERENCES "roles"("pk_id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rol_creacion_jerarquia" DROP CONSTRAINT "FK_06907d494f397996a2d85c0eb67"`);
        await queryRunner.query(`ALTER TABLE "rol_creacion_jerarquia" DROP CONSTRAINT "FK_1b25d18dffadb2e4dbbf66c901c"`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" DROP CONSTRAINT "FK_ef10d9983fcb45f0024cc7000d3"`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" DROP CONSTRAINT "FK_dc3cfbcce511233d4bef92d7e3b"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_1ab7dcfb69b30ddcdab1d564750"`);
        await queryRunner.query(`ALTER TABLE "finanzas_cosecha" DROP CONSTRAINT "FK_9ee882a201359367555803d307b"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_8a915d5adf1b954fc3fb4469a2d"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_ed669516597c2d98f49817c9814"`);
        await queryRunner.query(`ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "FK_b635c8408938f63578ad3a441d5"`);
        await queryRunner.query(`ALTER TABLE "epa" DROP CONSTRAINT "FK_25cd948e2b067f238871a478ce7"`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_epa" DROP CONSTRAINT "FK_e93725ad163564397db9100ca2d"`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_epa" DROP CONSTRAINT "FK_62ec7f2dad568439e62f7896b73"`);
        await queryRunner.query(`ALTER TABLE "venta" DROP CONSTRAINT "FK_1b5df15fa07acae8d18b095d5dc"`);
        await queryRunner.query(`ALTER TABLE "cosechas" DROP CONSTRAINT "FK_07c03f265c04076ea27e439632d"`);
        await queryRunner.query(`ALTER TABLE "cosechas_ventas" DROP CONSTRAINT "FK_5563c73e32fef530f3a140ce3bd"`);
        await queryRunner.query(`ALTER TABLE "cosechas_ventas" DROP CONSTRAINT "FK_bade37bec1231cf147fbcac413e"`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" DROP CONSTRAINT "FK_df819fa89f42a3fb674de12574e"`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" DROP CONSTRAINT "FK_959fe9d6787940b232ff5442540"`);
        await queryRunner.query(`ALTER TABLE "cultivos_variedad_x_zona" DROP CONSTRAINT "FK_bedc232cd8a0b1aba926d53af68"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_40f52a18a6b1e8efd9a4938bfec"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_4ff147ed17e8bdeb0a22232cf5b"`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" DROP CONSTRAINT "FK_48e34f436100b175050202792d5"`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" DROP CONSTRAINT "FK_b504e905dc2a3de3a0500e8973d"`);
        await queryRunner.query(`ALTER TABLE "reservas_x_actividad" DROP CONSTRAINT "FK_b7a58e288f2aff52bf3ac2eb6c3"`);
        await queryRunner.query(`ALTER TABLE "lotes_inventario" DROP CONSTRAINT "FK_378dc45fa7f862f19f316d5dd06"`);
        await queryRunner.query(`ALTER TABLE "lotes_inventario" DROP CONSTRAINT "FK_48dcf6942ce0b80afc4e30c7f80"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_ba1bbf9b0181a3be093de57a6f8"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_a3004a9c834ee05f56e3b3b921c"`);
        await queryRunner.query(`ALTER TABLE "usuarios_x_actividades" DROP CONSTRAINT "FK_399398e334d7c22d172a9a4fb9b"`);
        await queryRunner.query(`ALTER TABLE "usuarios_x_actividades" DROP CONSTRAINT "FK_58a5178734438394ee03a24949a"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_2b6534c9d14ac35826764cdc118"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_dec89f7cdc37cf746fc82ff6034"`);
        await queryRunner.query(`ALTER TABLE "permisos" DROP CONSTRAINT "FK_1def2cd2fbc57f21d1547db508c"`);
        await queryRunner.query(`ALTER TABLE "recursos" DROP CONSTRAINT "FK_f24d13798abb62d00be138dfc83"`);
        await queryRunner.query(`ALTER TABLE "sensor" DROP CONSTRAINT "FK_317e3ed127d5183a466383d910b"`);
        await queryRunner.query(`ALTER TABLE "sensor" DROP CONSTRAINT "FK_48052e061c57447d62f9e64b3da"`);
        await queryRunner.query(`ALTER TABLE "medicion_sensor" DROP CONSTRAINT "FK_a02dcc38c6502973912168b35b4"`);
        await queryRunner.query(`ALTER TABLE "zona_mqtt_config" DROP CONSTRAINT "FK_6f9527f65f4d638fef8bfe33e8f"`);
        await queryRunner.query(`ALTER TABLE "zona_mqtt_config" DROP CONSTRAINT "FK_3ae20521bac657fa2aab70ea611"`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_variedad" DROP CONSTRAINT "FK_f625a8d56b4c1e1f18fa2ad8bc7"`);
        await queryRunner.query(`ALTER TABLE "cultivos_x_variedad" DROP CONSTRAINT "FK_3869d84e502689591c987724be9"`);
        await queryRunner.query(`ALTER TABLE "variedad" DROP CONSTRAINT "FK_32531335d0482591eae661efcbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06907d494f397996a2d85c0eb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b25d18dffadb2e4dbbf66c901"`);
        await queryRunner.query(`DROP TABLE "rol_creacion_jerarquia"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef10d9983fcb45f0024cc7000d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc3cfbcce511233d4bef92d7e3"`);
        await queryRunner.query(`DROP TABLE "roles_permisos"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "finanzas_cosecha"`);
        await queryRunner.query(`DROP TABLE "movimientos_inventario"`);
        await queryRunner.query(`DROP TABLE "tipo_epa"`);
        await queryRunner.query(`DROP TABLE "epa"`);
        await queryRunner.query(`DROP TABLE "cultivos_x_epa"`);
        await queryRunner.query(`DROP TABLE "tipos_movimiento"`);
        await queryRunner.query(`DROP TABLE "venta"`);
        await queryRunner.query(`DROP TABLE "cosechas"`);
        await queryRunner.query(`DROP TABLE "cosechas_ventas"`);
        await queryRunner.query(`DROP TABLE "cultivos_variedad_x_zona"`);
        await queryRunner.query(`DROP TABLE "estados_fenologicos"`);
        await queryRunner.query(`DROP TABLE "actividades"`);
        await queryRunner.query(`DROP TABLE "reservas_x_actividad"`);
        await queryRunner.query(`DROP TABLE "estados_reserva"`);
        await queryRunner.query(`DROP TABLE "lotes_inventario"`);
        await queryRunner.query(`DROP TABLE "bodega"`);
        await queryRunner.query(`DROP TABLE "productos"`);
        await queryRunner.query(`DROP TABLE "unidades_medida"`);
        await queryRunner.query(`DROP TABLE "categoria"`);
        await queryRunner.query(`DROP TABLE "categoria_actividad"`);
        await queryRunner.query(`DROP TABLE "usuarios_x_actividades"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "fichas"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permisos"`);
        await queryRunner.query(`DROP TABLE "recursos"`);
        await queryRunner.query(`DROP TABLE "modulos"`);
        await queryRunner.query(`DROP TABLE "zonas"`);
        await queryRunner.query(`DROP TABLE "sensor"`);
        await queryRunner.query(`DROP TABLE "medicion_sensor"`);
        await queryRunner.query(`DROP TABLE "zona_mqtt_config"`);
        await queryRunner.query(`DROP TABLE "mqtt_config"`);
        await queryRunner.query(`DROP TABLE "tipo_sensor"`);
        await queryRunner.query(`DROP TABLE "cultivos_x_variedad"`);
        await queryRunner.query(`DROP TABLE "variedad"`);
        await queryRunner.query(`DROP TABLE "tipo_cultivo"`);
        await queryRunner.query(`DROP TABLE "cultivos"`);
    }

}
